import React, { useState } from 'react';
import { BarChart2, Download, Phone, Loader2 } from 'lucide-react';
import { GlassCard } from './ui/GlassCard';
import { HelplineModal } from './HelplineModal';

export function ActionButtons({ data }) {
    const [loadingAnalysis, setLoadingAnalysis] = useState(false);
    const [narrative, setNarrative] = useState(null);
    const [isHelplineOpen, setIsHelplineOpen] = useState(false);

    const handleFullAnalysis = async () => {
        if (!data) return;
        setLoadingAnalysis(true);
        setNarrative(null);
        try {
            const res = await fetch('http://localhost:8000/api/full-analysis', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            });
            const result = await res.json();
            setNarrative(result.narrative);
        } catch (error) {
            console.error("Analysis Failed:", error);
            setNarrative("Analysis failed to generate. Please ensure the backend is running.");
        } finally {
            setLoadingAnalysis(false);
        }
    };

    const handleDownloadReport = () => {
        if (!data) return;

        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const reportContent = `ManTacAi Forensic Analysis Report
================================
Generated: ${new Date().toLocaleString()}

RISK ASSESSMENT
--------------
Level: ${data.risk_level}
Score: ${(data.risk_score * 100).toFixed(1)}%
Primary Pattern: ${data.primary_pattern}
Active Phase: ${data.cycle_phase}
DARVO Index: ${data.darvo_score.toFixed(2)}

TACTIC FINGERPRINT
------------------
${data.radar_chart_data?.map(t => `${t.subject}: ${t.A}%`).join('\n') || 'No radar data available'}

SESSION TIMELINE (RISK)
-----------------------
${data.timeline?.map(t => `[${t.time}] Risk: ${(t.risk * 100).toFixed(1)}%`).join('\n') || 'No timeline data'}

*This report is generated by an automated system and is intended for informational/forensic use only.*
`;

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `mantacai_report_${timestamp}.txt`;
        document.body.appendChild(a);
        a.click();

        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    };

    return (
        <div className="flex flex-col gap-3 w-full">
            <button
                onClick={handleFullAnalysis}
                disabled={loadingAnalysis}
                className="w-full relative group cursor-pointer overflow-hidden rounded-xl border border-neon-cyan/30 bg-black/60 px-6 py-4 text-left transition-all hover:border-neon-cyan hover:bg-neon-cyan/5 hover:shadow-[0_0_15px_rgba(0,255,255,0.15)]"
            >
                <div className="absolute inset-0 bg-gradient-to-r from-neon-cyan/10 to-transparent translate-x-[-100%] group-hover:translate-x-0 transition-transform duration-500 ease-in-out" />
                <div className="relative z-10 font-orbitron text-neon-cyan/80 group-hover:text-neon-cyan flex items-center justify-between">
                    <span className="tracking-widest uppercase text-sm font-semibold">
                        {loadingAnalysis ? "Analyzing Patterns..." : "Full Analysis"}
                    </span>
                    {loadingAnalysis ? <Loader2 className="animate-spin" size={20} /> : <BarChart2 size={20} />}
                </div>
            </button>

            {narrative && (
                <GlassCard className="p-4 border border-neon-cyan/50 bg-black/80 animate-in fade-in slide-in-from-top-4 duration-500">
                    <p className="font-sans text-slate-300 text-sm leading-relaxed">
                        {narrative}
                    </p>
                </GlassCard>
            )}

            <button
                onClick={handleDownloadReport}
                className="w-full relative group cursor-pointer overflow-hidden rounded-xl border border-slate-700/50 bg-black/60 px-6 py-4 text-left transition-all hover:border-slate-500 hover:bg-slate-800/50"
            >
                <div className="absolute inset-0 bg-gradient-to-r from-slate-500/10 to-transparent translate-x-[-100%] group-hover:translate-x-0 transition-transform duration-500 ease-in-out" />
                <div className="relative z-10 font-orbitron text-slate-400 group-hover:text-slate-200 flex items-center justify-between">
                    <span className="tracking-widest uppercase text-sm font-semibold">Download Report</span>
                    <Download size={20} />
                </div>
            </button>

            <button
                onClick={() => setIsHelplineOpen(true)}
                className="w-full relative group cursor-pointer overflow-hidden rounded-xl border border-rose-500/30 bg-black/60 px-6 py-4 text-left transition-all hover:border-rose-500 hover:bg-rose-500/5 hover:shadow-[0_0_15px_rgba(244,63,94,0.15)] mt-2"
            >
                <div className="absolute inset-0 bg-gradient-to-r from-rose-500/10 to-transparent translate-x-[-100%] group-hover:translate-x-0 transition-transform duration-500 ease-in-out" />
                <div className="relative z-10 font-orbitron text-rose-500/80 group-hover:text-rose-500 flex items-center justify-between">
                    <span className="tracking-widest uppercase text-sm font-semibold">Emergency Helpline</span>
                    <Phone size={20} />
                </div>
                <div className="relative z-10 font-sans text-xs text-rose-500/60 group-hover:text-rose-400 mt-1">
                    Connect with support immediately
                </div>
            </button>

            <HelplineModal
                isOpen={isHelplineOpen}
                onClose={() => setIsHelplineOpen(false)}
            />
        </div>
    );
}
