
import os
from docx import Document
from docx.shared import Pt, RGBColor
from datetime import datetime

def generate_word_report(analysis_state, output_filename="ManTacAi_Report.docx"):
    """
    Generates a formatted Word document from the analysis state.
    Returns the absolute path to the generated file.
    """
    document = Document()
    
    # Title
    title = document.add_heading('Manipulation Tactic Detector - Analyis Report', 0)
    title.alignment = 1 # Center
    
    # Metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    document.add_paragraph(f"Generated on: {timestamp}")
    
    # 1. Executive Summary
    document.add_heading('1. Executive Summary', level=1)
    
    risk_level = analysis_state.get("risk_level", "Unknown")
    pattern = analysis_state.get("pattern", "Unknown")
    darvo = analysis_state.get("darvo_score", 0.0)
    
    p = document.add_paragraph()
    p.add_run("Overall Risk Level: ").bold = True
    risk_run = p.add_run(risk_level)
    if risk_level in ["High", "Critical"]:
        risk_run.font.color.rgb = RGBColor(255, 0, 0) # Red
    elif risk_level == "Medium":
        risk_run.font.color.rgb = RGBColor(255, 165, 0) # Orange
    else:
        risk_run.font.color.rgb = RGBColor(0, 128, 0) # Green
        
    p = document.add_paragraph()
    p.add_run("Primary Pattern Detected: ").bold = True
    p.add_run(pattern)
    
    p = document.add_paragraph()
    p.add_run("DARVO Score: ").bold = True
    p.add_run(f"{darvo:.2f} / 1.0")

    # 2. Input Messages
    document.add_heading('2. Analyzed Messages', level=1)
    messages = analysis_state.get("messages", [])
    if messages:
        for i, msg in enumerate(messages, 1):
            document.add_paragraph(f"Message {i}: \"{msg}\"", style='Quote')
    else:
        document.add_paragraph("No valid messages were processed.")

    # 3. Detailed Tactics
    document.add_heading('3. Detailed Tactic Breakdown', level=1)
    predictions = analysis_state.get("predictions", {})
    if predictions:
        sorted_preds = sorted(predictions.items(), key=lambda x: x[1], reverse=True)[:3]
        for label, prob in sorted_preds:
            p = document.add_paragraph(style='List Bullet')
            label_name = label.replace("_", " ").title()
            p.add_run(f"{label_name}: ").bold = True
            p.add_run(f"{int(prob*100)}% Confidence")
    else:
        document.add_paragraph("No specific tactics detected with high confidence.")

    # 4. DARVO Analysis
    document.add_heading('4. DARVO Pattern Analysis', level=1)
    if darvo > 0.6:
        p = document.add_paragraph()
        p.add_run("Status: HIGH Likelihood").bold = True
        p.font.color.rgb = RGBColor(255, 0, 0)
        document.add_paragraph("The analysis detected a significant presence of Deny, Attack, and Reverse Victim/Offender tactics.")
    elif darvo > 0.3:
        p = document.add_paragraph()
        p.add_run("Status: Moderate Likelihood").bold = True
        document.add_paragraph("Some elements of DARVO were detected.")
    else:
        document.add_paragraph("No significant DARVO pattern detected.")

    # 5. Safety Context
    checklist = analysis_state.get("safety_checklist", [])
    if checklist:
        document.add_heading('5. Safety Context (Self-Reported)', level=1)
        for item in checklist:
            document.add_paragraph(item, style='List Bullet')

    # Footer / Disclaimer
    document.add_page_break()
    document.add_paragraph("Disclaimer: This report is generated by an AI tool for educational purposes only. It is not a professional advice.")
    
    # Save
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    output_path = os.path.join(base_dir, output_filename)
    document.save(output_path)
    
    return output_path
