
import datetime

def generate_full_report(messages, predictions, risk_level, detected_pattern, darvo_score, safety_checklist):
    """
    Generates a detailed markdown report of the analysis.
    """
    # 1. Header
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    report = f"# 📄 Analysis Report\n"
    report += f"**Date:** {timestamp}\n\n"
    
    # 2. Executive Summary
    report += "## 1. Executive Summary\n"
    report += f"**Overall Risk Level:** {risk_level}\n"
    report += f"**Primary Pattern Detected:** {detected_pattern}\n"
    report += f"**DARVO Score:** {darvo_score:.2f} / 1.0\n\n"
    
    # 3. Message Analysis
    report += "## 2. Input Analysis\n"
    report += f"Analyzed {len(messages)} message(s).\n\n"
    
    # 4. Detailed Findings (Top 3 Tactics)
    report += "## 3. Detailed Tactic Breakdown\n"
    if predictions:
        # Sort by probability
        sorted_preds = sorted(predictions.items(), key=lambda x: x[1], reverse=True)
        top_3 = sorted_preds[:3]
        
        for label, prob in top_3:
            percentage = int(prob * 100)
            # Format label name
            label_name = label.replace("_", " ").title()
            report += f"*   **{label_name}:** {percentage}% Confidence\n"
    else:
        report += "*   No specific tactics detected (Low confidence).\n"
    report += "\n"

    # 5. DARVO Explanation
    report += "## 4. DARVO Pattern Analysis\n"
    if darvo_score > 0.6:
        report += "**Status: HIGH Likelihood**\n"
        report += "The analysis detected a significant presence of Deny, Attack, and Reverse Victim/Offender tactics. This suggests a sophisticated manipulation strategy aimed at shifting blame.\n"
    elif darvo_score > 0.3:
        report += "**Status: Moderate Likelihood**\n"
        report += "Some elements of DARVO were detected. Watch for shifts in the narrative where the offender claims to be the victim.\n"
    else:
        report += "**Status: Low Likelihood**\n"
        report += "No significant DARVO pattern detected.\n"
    report += "\n"

    # 6. Safety Context
    if safety_checklist:
        report += "## 5. Safety Context (Self-Reported)\n"
        report += "You identified the following risk factors:\n"
        for item in safety_checklist:
            report += f"*   {item}\n"
        report += "\n"

    # 7. Disclaimer
    report += "---\n"
    report += "*Disclaimer: This report is generated by an AI tool for educational purposes only. It is not a professional psychological diagnosis or legal advice. If you feel unsafe, please contact emergency services (112) or the helpline (181).*"
    
    return report
